### ISSUE TITLE
Standard pitch A'

### ISSUE THREAD

**Issue by sebo361** [qiuxiang/tuner#10]
Hi @qiuxiang, great work with this tuner!

Which standard pitch A' did you use as default setting in this tuner? Usually musicians in an orchestra agree on a standard pitch A' like 443 hz. Others agree on 440 or 442. Is there a possibility to set this before tuning?

**Comment by qiuxiang** [comment]
The middle A is 440:
https://github.com/qiuxiang/tuner/blob/ac9782a7c08f4e7b45ef57411f523d6f6c658592/app/tuner.js#L2

**Comment by sebo361** [comment]
Thanks a lot for the quick response @qiuxiang! A nice additional feature for this tuner would be to allow the user to set this middle A for his/her requirements. Maybe with a kind of slider below the tuner like this: 
![88799207-c5b96e00-d1ae-11ea-891d-ec7df398730e](https://user-images.githubusercontent.com/29478970/88799293-ec77a480-d1ae-11ea-82ca-64bd06c69eb8.png)

**Comment by qiuxiang** [comment]
Okey, this is the next feature to be implemented

**Comment by sebo361** [comment]
Awesome thanks @qiuxiang! When do you think you will have time for implementing it? Just wondering when I can use this feature :)

**Comment by qiuxiang** [comment]
Not sure, maybe one week

**Comment by sebo361** [comment]
So cool thanks!

**Comment by qiuxiang** [comment]
## Click here:
![image](https://user-images.githubusercontent.com/1709072/89747250-7e0cdd80-daf0-11ea-9b1d-02b0b2ba5973.png)

## Then u can set the A4:
![image](https://user-images.githubusercontent.com/1709072/89747264-941a9e00-daf0-11ea-9179-22418c5a6480.png)

**Comment by sebo361** [comment]
Amazing thanks so much @qiuxiang !!
