### ISSUE TITLE
Doesn't seem to work on an iPhone in any browser

### ISSUE THREAD

**Issue by dezman** [qiuxiang/tuner#3]
It seems very close to working in Safari.
It asks for microphone permission and then sits at 440 Hz.

![screen shot 2018-03-15 at 2 14 44 pm](https://user-images.githubusercontent.com/9451001/37491479-3c7ac336-285b-11e8-98e9-601667c483a2.png)

Any ideas about how to get it working? I'd love to help out also if you can point me in the right direction.

**Comment by dezman** [comment]
Also there do not appear to be any errors in the console when I inspect it by connecting to my phone with safari on my mac.

**Comment by qiuxiang** [comment]
`getUserMedia` is not yet supported on iOS when this app developing. Thanks for your reminder that iOS 11.2 already supported.

Then I found some discussions pointing out some gotchas with iOS: https://stackoverflow.com/a/47562955.

**Comment by qiuxiang** [comment]
Fixed
